name: Nix Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: DeterminateSystems/determinate-nix-action@v3.20.0
    - uses: DeterminateSystems/magic-nix-cache-action@v14
      with:
        use-flakehub: false

    - name: Build Nix Package
      run: nix build . -L --log-format bar-with-logs
